force-app/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <label>Repair Order</label>
    <nameField>
        <label>Repair Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReplacementPart__c/ReplacementPart__c.object-meta.xml
<CustomObject>
    <label>Replacement Part</label>
    <nameField>
        <label>Replacement Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replacement Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReplacementPart__c/fields/RepairOrder__c.field-meta.xml
<CustomField>
    <fullName>RepairOrder__c</fullName>
    <label>Repair Order</label>
    <referenceTo>RepairOrder__c</referenceTo>
    <relationshipLabel>Replacement Parts</relationshipLabel>
    <relationshipName>ReplacementParts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReplacementPart__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReplacementPartController_Selector.cls
public with sharing class ReplacementPartController_Selector {
  public static List<ReplacementPart__c> getReplacementParts(
    String repOrderId
  ) {
    List<ReplacementPart__c> replacementParts = new List<ReplacementPart__c>();
    if (
      Schema.SObjectType.ReplacementPart__c.isAccessible() && // Verifica se o objeto ReplacementPart__c é acessível
      Schema.SObjectType.ReplacementPart__c.isQueryable()     // Verifica se o objeto ReplacementPart__c pode ser consultado
    ) {
      replacementParts = [
        SELECT Id, Name, Stock__c, UnitCost__c
        FROM ReplacementPart__c
        // WHERE RepairOrder__c = :repOrderId  // Filtra os ReplacementPart__c por RepairOrder__c usando o repOrderId
      ];
    }
    return replacementParts;
  }
}